<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="FunMusicTestSuite" duration-ms="48550" started-at="2016-02-25T07:32:36Z" finished-at="2016-02-25T07:33:24Z">
    <groups>
    </groups>
    <test name="FunMusicTest" duration-ms="48550" started-at="2016-02-25T07:32:36Z" finished-at="2016-02-25T07:33:24Z">
      <class name="com.ylss.test.SimpleTest">
        <test-method status="PASS" signature="test()[pri:0, instance:com.ylss.test.SimpleTest@3a03464]" name="test" duration-ms="5173" started-at="2016-02-25T15:33:04Z" finished-at="2016-02-25T15:33:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- com.ylss.test.SimpleTest -->
      <class name="com.ylss.test.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.ylss.test.LoginTest@4909b8da]" name="setUp" is-config="true" duration-ms="11945" started-at="2016-02-25T15:32:24Z" finished-at="2016-02-25T15:32:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginIn()[pri:0, instance:com.ylss.test.LoginTest@4909b8da]" name="loginIn" duration-ms="28124" started-at="2016-02-25T15:32:36Z" finished-at="2016-02-25T15:33:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginIn -->
        <test-method status="FAIL" signature="loginOut()[pri:0, instance:com.ylss.test.LoginTest@4909b8da]" name="loginOut" duration-ms="12789" started-at="2016-02-25T15:33:09Z" depends-on-methods="com.ylss.test.LoginTest.loginIn" finished-at="2016-02-25T15:33:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.ylss.test.LoginTest.loginOut(LoginTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginOut -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.ylss.test.LoginTest@4909b8da]" name="tearDown" is-config="true" duration-ms="1047" started-at="2016-02-25T15:33:25Z" finished-at="2016-02-25T15:33:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.ylss.test.LoginTest -->
    </test> <!-- FunMusicTest -->
  </suite> <!-- FunMusicTestSuite -->
</testng-results>
